name: mtm
description: Mtm radio project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.4
  global_configuration: ^2.0.0-nullsafety.1
  provider: ^6.0.2
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  intl: ^0.17.0
  http: ^0.13.3
  shared_preferences: ^2.0.7
  equatable: ^2.0.3
  flutter_secure_storage: ^5.0.2
  get: 4.5.1
  flutter_localized_locales: ^2.0.3
  rxdart: ^0.27.3
  image_picker: ^0.8.4+1
  flutter_rating_bar: ^4.0.0
  sqflite: ^2.0.2
  path_provider: ^2.0.2
  connectivity_plus: ^2.1.0
  meta: ^1.3.0
  cached_network_image: ^3.2.0
  animation_wrappers: ^3.0.0
  lottie: 1.2.2
  firebase_messaging: ^14.1.0
  firebase_core: ^2.2.0
  full_screen_image_null_safe: ^2.0.0
  flutter_html: ^2.2.1
  video_player: ^2.4.8
  url_launcher: ^6.1.7
  permission_handler: ^10.2.0
  image_gallery_saver: ^1.7.1
  dio: ^4.0.6
  audioplayers: ^0.20.1

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  scrollable_positioned_list: ^0.2.3
  carousel_slider: ^4.0.0
  font_awesome_flutter: ^10.1.0

flutter_launcher_name:
  name: "Aliento FM"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/cfg/
    - assets/img/
    - assets/img/galeria/
    - assets/img/patrocinadores/
    - assets/video/
    - assets/img/jar-loading.gif
    - assets/img/user.png
    - assets/icons/
    - assets/icons/home.png

